version: '3.3'

services:
  tiggomark_db:
    image: mysql:8.0
    container_name: mysql_tiggomark_prod
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '321.qwerty'
      MYSQL_DATABASE: 'tiggomark'
      MYSQL_USER: 'admin'
      MYSQL_TCP_PORT: '3309'
      MYSQL_PASSWORD: '321.qwerty'
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3309:3309"

  tiggomark:
    image: tiggomark/projects:1.0
    container_name: tiggomark_prod
    restart: always
    environment:
      LEAN_APP_URL: 'https://vpn.tiggomark.com.br'                     # Only needed for subdirectory setup; protocol (http or https) and base URL , trailing slash not needed
      LEAN_SITENAME: 'Tiggomark'                                         # Name of your site, can be changed later
      LEAN_DB_HOST: 'mysql_tiggomark_prod'                                    # Database host, derived from container_name in tiggomark_db container
      LEAN_DB_USER: 'admin'
      LEAN_DB_PASSWORD: '321.qwerty'
      LEAN_DB_PORT: 3309
      LEAN_DB_DATABASE: 'tiggomark'
      LEAN_DEFAULT_TIMEZONE: 'Europe/Stockholm'                         # Set default server timezone
      LEAN_SESSION_PASSWORD: 'GD8Fozemg3AqM9my86TTfgTeGPXXkPF7'         # Salting sessions. Replace with a strong password
      LEAN_SESSION_EXPIRATION: 28800                                    # How many seconds after inactivity should we logout?  28800seconds = 8hours
    volumes:
      - public_userfiles2:/var/www/html/public/userfiles
      - userfiles2:/var/www/html/userfiles
    ports:
      - "7575:80"                                                       # The port to expose and access tiggomark
    depends_on:
      - tiggomark_db                                                     # Don't start tiggomark unless tiggomark_db is running

  tiggomark_frpc:
    image: tiggomark/frpc_prod:latest
    container_name: tiggomark_frpc
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - tiggomark

volumes:
  db_data:
  userfiles2:
  public_userfiles2:



