version: '3.3'

services:
  tiggomark_db:
    image: mysql:8.0
    container_name: mysql_tiggomark_dev
    environment:
      MYSQL_ROOT_PASSWORD: '321.qwerty'
      MYSQL_DATABASE: 'tiggomark'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '321.qwerty'
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"

  tiggomark:
    build: .
    container_name: tiggomark11
    restart: unless-stopped
    environment:
      # LEAN_APP_URL: 'https://domain.com/tiggomark'                     # Only needed for subdirectory setup; protocol (http or https) and base URL , trailing slash not needed
      LEAN_SITENAME: 'tiggomark2'                                         # Name of your site, can be changed later
      LEAN_DB_HOST: 'mysql_tiggomark_dev'                                    # Database host, derived from container_name in tiggomark_db container
      LEAN_DB_USER: 'admin'
      LEAN_DB_PASSWORD: '321.qwerty'
      LEAN_DB_DATABASE: 'tiggomark'
      LEAN_DB_PORT: 3306
      LEAN_DEFAULT_TIMEZONE: 'Europe/Stockholm'                         # Set default server timezone
      LEAN_SESSION_PASSWORD: 'GD8Fozemg3AqM9my86TTfgTeGPXXkPF7'         # Salting sessions. Replace with a strong password
      LEAN_SESSION_EXPIRATION: 28800                                    # How many seconds after inactivity should we logout?  28800seconds = 8hours

    ports:
      - "8080:80"                                                       # The port to expose and access tiggomark
    depends_on:
      - tiggomark_db                                                     # Don't start tiggomark unless tiggomark_db is running


